### ISSUE TITLE
[Issue] logo.png is corrupted

### ISSUE THREAD

**Issue by Mechalopa** [nanite/Trenzalore#4]
### Minecraft Version

1.21.1

### Modloader

neoforge-21.1.54

### Mod version

6.1.1+mc1.21.1

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

None

### Description of the issue you are having

As the title says, logo.png seems to be corrupted.
https://github.com/nanite/Trenzalore/blob/1.21/common/src/main/resources/assets/trenzalore/logo.png

### Information

- [X] I have provided as much information as possible

**Comment by yannick-was-taken** [comment]
When [Catalogue mod menu](https://www.curseforge.com/minecraft/mc-mods/catalogue) is installed, this issue produces a crash when the list entry is being rendered. Minimal reproduction mod folder is attached.

Interestingly, when [Prism](https://www.curseforge.com/minecraft/mc-mods/prism-lib) (or Trenzalore) is removed, the crash does not occur, it only occurs with both mods present.
![Screenshot_2024-09-18_11-06-07](https://github.com/user-attachments/assets/3f2c6681-98b3-4b7d-9528-5c26aa4df2f4)

Versions are the same as w/ initial reporter.

The exception just specifies a corrupt PNG being loaded, but is attached for reference as well.
```
[18Sep2024 11:14:10.478] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Rendering screen
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1120) ~[client-1.21.1-20240808.144430-srg.jar%23171!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.runTick(Minecraft.java:1195) ~[client-1.21.1-20240808.144430-srg.jar%23171!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21.1-20240808.144430-srg.jar%23171!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21.1-20240808.144430-srg.jar%23171!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.24.jar%2398!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.24.jar%2398!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.24.jar%2398!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.24.jar%2398!/:4.0]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23122!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23122!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23122!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23122!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23122!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23122!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23122!/:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]
Caused by: java.lang.RuntimeException: java.io.IOException: Could not load image: Corrupt PNG
	at TRANSFORMER/catalogue@1.10.2/com.mrcrayfish.catalogue.platform.NeoForgePlatformHelper.loadNativeImage(NeoForgePlatformHelper.java:64) ~[catalogue-neoforge-1.21.1-1.10.2.jar%23173!/:?]
	at TRANSFORMER/catalogue@1.10.2/com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen.loadAndCacheIcon(CatalogueModListScreen.java:608) ~[catalogue-neoforge-1.21.1-1.10.2.jar%23173!/:?]
	at TRANSFORMER/catalogue@1.10.2/com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen$ModListEntry.render(CatalogueModListScreen.java:793) ~[catalogue-neoforge-1.21.1-1.10.2.jar%23173!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.components.AbstractSelectionList.renderItem(AbstractSelectionList.java:447) ~[client-1.21.1-20240808.144430-srg.jar%23171!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.components.AbstractSelectionList.renderListItems(AbstractSelectionList.java:432) ~[client-1.21.1-20240808.144430-srg.jar%23171!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.components.AbstractSelectionList.renderWidget(AbstractSelectionList.java:188) ~[client-1.21.1-20240808.144430-srg.jar%23171!/:?]
	at TRANSFORMER/catalogue@1.10.2/com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen$ModList.renderWidget(CatalogueModListScreen.java:740) ~[catalogue-neoforge-1.21.1-1.10.2.jar%23173!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.components.AbstractWidget.render(AbstractWidget.java:65) ~[client-1.21.1-20240808.144430-srg.jar%23171!/:?]
	at TRANSFORMER/catalogue@1.10.2/com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen.drawModList(CatalogueModListScreen.java:274) ~[catalogue-neoforge-1.21.1-1.10.2.jar%23173!/:?]
	at TRANSFORMER/catalogue@1.10.2/com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen.renderBackground(CatalogueModListScreen.java:190) ~[catalogue-neoforge-1.21.1-1.10.2.jar%23173!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.Screen.render(Screen.java:122) ~[client-1.21.1-20240808.144430-srg.jar%23171!/:?]
	at TRANSFORMER/catalogue@1.10.2/com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen.render(CatalogueModListScreen.java:198) ~[catalogue-neoforge-1.21.1-1.10.2.jar%23173!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.Screen.renderWithTooltip(Screen.java:112) ~[client-1.21.1-20240808.144430-srg.jar%23171!/:?]
	at TRANSFORMER/neoforge@21.1.54/net.neoforged.neoforge.client.ClientHooks.drawScreenInternal(ClientHooks.java:428) ~[neoforge-21.1.54-universal.jar%23172!/:?]
	at TRANSFORMER/neoforge@21.1.54/net.neoforged.neoforge.client.ClientHooks.drawScreen(ClientHooks.java:422) ~[neoforge-21.1.54-universal.jar%23172!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1092) ~[client-1.21.1-20240808.144430-srg.jar%23171!/:?]
	... 18 more
Caused by: java.io.IOException: Could not load image: Corrupt PNG
	at TRANSFORMER/minecraft@1.21.1/com.mojang.blaze3d.platform.NativeImage.read(NativeImage.java:147) ~[client-1.21.1-20240808.144430-srg.jar%23171!/:?]
	at TRANSFORMER/minecraft@1.21.1/com.mojang.blaze3d.platform.NativeImage.read(NativeImage.java:111) ~[client-1.21.1-20240808.144430-srg.jar%23171!/:?]
	at TRANSFORMER/minecraft@1.21.1/com.mojang.blaze3d.platform.NativeImage.read(NativeImage.java:102) ~[client-1.21.1-20240808.144430-srg.jar%23171!/:?]
	at TRANSFORMER/catalogue@1.10.2/com.mrcrayfish.catalogue.platform.NeoForgePlatformHelper.loadNativeImage(NeoForgePlatformHelper.java:58) ~[catalogue-neoforge-1.21.1-1.10.2.jar%23173!/:?]
	at TRANSFORMER/catalogue@1.10.2/com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen.loadAndCacheIcon(CatalogueModListScreen.java:608) ~[catalogue-neoforge-1.21.1-1.10.2.jar%23173!/:?]
	at TRANSFORMER/catalogue@1.10.2/com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen$ModListEntry.render(CatalogueModListScreen.java:793) ~[catalogue-neoforge-1.21.1-1.10.2.jar%23173!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.components.AbstractSelectionList.renderItem(AbstractSelectionList.java:447) ~[client-1.21.1-20240808.144430-srg.jar%23171!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.components.AbstractSelectionList.renderListItems(AbstractSelectionList.java:432) ~[client-1.21.1-20240808.144430-srg.jar%23171!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.components.AbstractSelectionList.renderWidget(AbstractSelectionList.java:188) ~[client-1.21.1-20240808.144430-srg.jar%23171!/:?]
	at TRANSFORMER/catalogue@1.10.2/com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen$ModList.renderWidget(CatalogueModListScreen.java:740) ~[catalogue-neoforge-1.21.1-1.10.2.jar%23173!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.components.AbstractWidget.render(AbstractWidget.java:65) ~[client-1.21.1-20240808.144430-srg.jar%23171!/:?]
	at TRANSFORMER/catalogue@1.10.2/com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen.drawModList(CatalogueModListScreen.java:274) ~[catalogue-neoforge-1.21.1-1.10.2.jar%23173!/:?]
	at TRANSFORMER/catalogue@1.10.2/com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen.renderBackground(CatalogueModListScreen.java:190) ~[catalogue-neoforge-1.21.1-1.10.2.jar%23173!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.Screen.render(Screen.java:122) ~[client-1.21.1-20240808.144430-srg.jar%23171!/:?]
	at TRANSFORMER/catalogue@1.10.2/com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen.render(CatalogueModListScreen.java:198) ~[catalogue-neoforge-1.21.1-1.10.2.jar%23173!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.Screen.renderWithTooltip(Screen.java:112) ~[client-1.21.1-20240808.144430-srg.jar%23171!/:?]
	at TRANSFORMER/neoforge@21.1.54/net.neoforged.neoforge.client.ClientHooks.drawScreenInternal(ClientHooks.java:428) ~[neoforge-21.1.54-universal.jar%23172!/:?]
	at TRANSFORMER/neoforge@21.1.54/net.neoforged.neoforge.client.ClientHooks.drawScreen(ClientHooks.java:422) ~[neoforge-21.1.54-universal.jar%23172!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1092) ~[client-1.21.1-20240808.144430-srg.jar%23171!/:?]
	... 18 more
```
